name: Container Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  scan:
    name: Scan Container Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List directory contents
        run: |
          pwd
          ls -R

      - name: Build an image from Dockerfile
        run: |
          if [ -f "Dockerfile" ]; then
            docker build -t my-docker-image:${{ github.sha }} .
          else
            echo "Dockerfile not found in the current directory"
            exit 1
          fi

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'my-docker-image:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'